### ISSUE TITLE
Cannot start command line tool

### ISSUE THREAD

**Issue by ayberk** [chrismattmann/nutch-python#8] opened 2015-10-12 23:55 UTC
Trying to start the command line tool due to 'bad args': 

```
➜  nutch git:(master) ✗ nutch-python
nutch.py: Error: Bad args
nutch.py:
A simple python client for Nutch using the Nutch server REST API.
Most commands return results in JSON format by default, or plain text.

To control Nutch, use:

-- from nutch.nutch import Nutch
-- nt = Nutch(crawlId,                           # name your crawl
              confId='default',                  # pick a known config. file
              urlDir='url/',                     # directory containing the seed URL list
              serverEndpoint='localhost:8001',   # endpoint where the Nutch server is running
              **args                             # additional key=value pairs to submit as args
             )
-- response, status = nt.<command>(**args)       # where commmand is in the set
                                                 # ['INJECT', 'GENERATE', 'FETCH', 'PARSE', 'UPDATEDB']
 or
-- status, response = nt.crawl(**args)    # will run the commands in order with echoing of reponses

Commands (which become Hadoop jobs):
  inject   - inject a URL seed list into a named crawl
  generate - general URL list
  fetch    - fetch inital set of web pages
  parse    - parse web pages and invoke Tika metadata extraction
  updatedb - update the crawl database

To get/set the configuration of the Nutch server, use:
-- nt.configGetList()                    # get list of named configurations
-- nt.configGetInfo(id)                  # get parameters in named config.
-- nt.configCreate(id, parameterDict)    # create a new named config.

To see the status of jobs, use:
-- nt.jobGetList()                       # get list of running jobs
-- nt.jobGetInfo(id)                     # get metadata for a job id
-- nt.jobStop(id)                        # stop a job, DANGEROUS!!, may corrupt segment files
```

It looks this is directly related to #4, I will be updating the documentation and main method accordingly if no one's on it.

**Comment by chrismattmann** [comment] 2015-10-13 01:54
please feel free to provide a doc PR would be happy to merge @ayberk !

**Comment by chrismattmann** [comment] 2015-10-13 03:19
This is a dupe of #3

**Comment by chrismattmann** [comment] 2015-10-13 03:19
@ayberk let's move the convo to #3.

**Closed as completed by chrismattmann** 2015-10-13 03:19 UTC
